language: csharp
mono: none
dotnet: 2.1.102

script:
  - dotnet run -p generator/src/generator.csproj -- . "https://fuseopen.com/docs/" _site
  - ./copy-assets.bash _site
  - find _site/media -type f \( -iname "*.png" -or -iname "*.jpg" \) -exec mogrify -strip -resize 450x450\> {} \;
  - find _site/media -type f -iname "*.png" -exec pngquant {} \; -exec optipng -silent {} \;
  - touch _site/.nojekyll

addons:
  apt:
    packages:
      - imagemagick
      - pngquant
      - optipng

deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
